### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by DaniilSokolyuk** [zawodskoj/GoddamnConsole#2]
Problem with very high usage of cpu (10-20%)
Problem is here: https://github.com/zawodskoj/GoddamnConsole/blob/master/GoddamnConsole/GoddamnConsole/NativeProviders/Windows/WindowsNativeConsoleProvider.cs#L182
I move this to beginning of the loop, and cpu usage down to 0%

**Comment by zawodskoj** [comment]
Спасибо за сообщение
Исправлено последним коммитом
Перенос Thread.Sleep в начало цикла действительно решает проблему, так как в случае неизменных размеров он не вызывается
